---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


#web servers
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes


# db servers
- hosts: db_servers
  become: true
  tasks: 
  
  - name: install mariadb package (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


# file servers
- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package
    package: 
      name: 
        - samba
      state: latest
