---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

#workstations
- hosts: workstations
  become: true
  roles:
    - workstations

#web servers
- hosts: web_servers
  become: true
  roles:
    - web_servers

# db servers
- hosts: db_servers
  become: true
  roles:
    - db_servers

# file servers
- hosts: file_servers
  become: true
  roles:
    - file_servers
