---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  remote_user: simone
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeLUPBwzB0OQ6Cy3m5Zqx5Z0z2wkTTaGSkFP5Ry7Al3 “ansible”"


- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    package: 
      name:
        - unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 755
      owner: root
      group: root



#web servers
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: start apache2 (CentOS)
    tags: apache, centOS, httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS" 

  - name: change email address for admin
    tags: apache, Ubuntu, httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@email.com
    when: ansible_distribution == "CentOS" 
    register: httpd

  - name: restart apache2 (CentOS)
    tags: apache, ubuntu, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 644


# db servers
- hosts: db_servers
  become: true
  tasks: 
  
  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


# file servers
- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package
    tags: samba
    package: 
      name: 
        - samba
      state: latest


