---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    package: 
      name:
        - unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 755
      owner: root
      group: root



#web servers
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 644


# db servers
- hosts: db_servers
  become: true
  tasks: 
  
  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


# file servers
- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package
    tags: samba
    package: 
      name: 
        - samba
      state: latest


